DEFAULT_LOCALE: "en"
OPEN_BROWSER: true # Whether the browser should be automatically opened when developing

COMPONENTS_PATH: 
  - "components"
  - "${SIBYL_PATH}/components"
LAYOUT_PATH:
  - "layouts"
  - "${SIBYL_PATH}/layouts"